services:
  backend:
    image: ghcr.io/matmridul/infinita-pipeline-backend:latest
    container_name: backend_service
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - backend.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    image: ghcr.io/matmridul/infinita-pipeline-frontend:latest
    container_name: frontend_service
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    # Uses Docker's existing registry auth; make sure you've done `docker login ghcr.io` once on the server
    command: --interval 30 --cleanup --rolling-restart --registry-auth frontend_service backend_service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
