services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      # add origins for dev if you need more than localhost:5173
      - ALLOWED_ORIGINS=
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules         # keep deps inside container (prevents volume shadowing)
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend
    restart: unless-stopped
